# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "aadd3440-8763-4c29-bac1-fa01a0494656"

default_platform :mac

lane :adhoc do
  # build your macOS app
  gym(
    scheme: "rvcmac",
    export_method: "ad-hoc"
  )
end
